[workspace]
members = [
    "hipvs",
    "hipvs-sys",
]
resolver = "2"

[workspace.package]
version = "25.6.0"
edition = "2021"
description = "AMD HIP Vector Search library"
authors = ["AMD"]
homepage = "https://github.com/ROCm-DS/hipVS"
license = "MIT and Apache-2.0"
repository = "https://github.com/ROCm-DS/hipVS"
